-- Script for Table Creation

create table "SHOPPINGCART".COMMENTS
(
	COMMENT_ID INTEGER not null primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	COMMENT VARCHAR(250) not null,
	USER_ID INTEGER,
	PRODUCT_ID INTEGER,
	CREATED_ON TIMESTAMP default CURRENT TIMESTAMP not null
)

create table "SHOPPINGCART".PRODUCT
(
	PRODUCT_ID INTEGER not null primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	PRODUCT_NAME VARCHAR(250) not null,
	PRODUCT_PRICE VARCHAR(250) not null,
	PRODUCT_CODE VARCHAR(250),
	PRODUCT_IMAGE VARCHAR(250),
	PRODUCT_QUANTITY INTEGER,
	IMAGE_PATH BLOB(2147483647),
	CREATED_ON TIMESTAMP default CURRENT TIMESTAMP not null,
	MODIFIED_ON TIMESTAMP default CURRENT TIMESTAMP not null,
	COMMENT VARCHAR(255)
)

create table "SHOPPINGCART".SHOPPING_CART
(
	CART_ID INTEGER not null primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	PRODUCT_ID INTEGER,
	USER_ID INTEGER,
	TOTAL_PRICE DOUBLE,
	QUANTITY INTEGER,
	CARD_REFERENCE VARCHAR(500),
	CREATED_ON TIMESTAMP default CURRENT TIMESTAMP not null,
	MODIFIED_ON TIMESTAMP default CURRENT TIMESTAMP not null
)

create table "SHOPPINGCART".USERS
(
	USER_ID INTEGER not null primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	USER_NAME VARCHAR(100),
	USER_ROLE VARCHAR(100),
	USER_PWD VARCHAR(100),
	CREATED_ON TIMESTAMP default CURRENT TIMESTAMP not null
)